const ADDTODO = 'ADDTODO'
const REMOVETODO = 'REMOVETODO'
const TOGGLETODO = 'TOGGLETODO'
const ALLTODO = 'ALLTODO'
const COMPONENTTODO = 'COMPONENTTODO'
const UNCOMPONENTTODO = 'UNCOMPONENTTODO'
const CHANGETYPE = "CHANGETYPE"
const FETCHNEWS = "FETCHNEWS"
export { ADDTODO, REMOVETODO, TOGGLETODO, ALLTODO, COMPONENTTODO, UNCOMPONENTTODO, CHANGETYPE, FETCHNEWS }
